version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: faker
    versions:
    - 5.1.0
    - 5.2.0
    - 5.3.1
    - 5.4.0
    - 5.5.1
    - 5.5.2
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.14
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@graphql-codegen/cli"
    versions:
    - 1.20.0
    - 1.20.1
    - 1.21.1
    - 1.21.2
    - 1.21.3
  - dependency-name: "@nestjs/platform-fastify"
    versions:
    - 7.6.11
    - 7.6.12
    - 7.6.13
    - 7.6.14
    - 7.6.5
    - 7.6.7
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@graphql-codegen/typescript-resolvers"
    versions:
    - 1.18.1
    - 1.18.2
    - 1.19.0
  - dependency-name: "@graphql-codegen/typescript"
    versions:
    - 1.20.0
    - 1.20.2
    - 1.21.0
    - 1.21.1
  - dependency-name: node-notifier
    versions:
    - 8.0.1
